[package]
name = "rumtk-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rumtk-core = { version = "0.10.4", path = "../rumtk-core" }
rumtk-web = { version = "0.4.9", path = "../rumtk-web" }
