[package]
name = "rumtk-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rumtk-core = { version = "0.9.14", path = "../rumtk-core" }
rumtk-web = { version = "0.3.6", path = "../rumtk-web" }
