[package]
name = "rumtk-benchmark"
version = "0.1.0"
edition = "2021"

[dependencies]
rumtk-core = { version = "0.12.0", path = "../rumtk-core" }
rumtk-web = { version = "0.4.45", path = "../rumtk-web" }
