[package]
name = "rumtk-web"
version = "0.1.0"
edition = "2024"

[dependencies]
#rumtk-core = { path = "../rumtk-core" }
rumtk-core = "0.9.6"
askama = "0.14.0"
axum = "0.8.7"
tokio = { version = "1.48.0", features = ["full"] }
tower-http = { version = "0.6.7", features = ["fs", "compression-full", "cors"] }
tracing = "0.1.41"
phf = "0.13.1"
phf_macros = "0.13.1"
clap = { version = "4.5.38", features = ["derive"] }
pulldown-cmark = "0.13.0"
serde = { version = "1.0.228", features = ["derive", "std"] }
serde_json = "1.0.145"
